##server:
##port:8081

##spring:
## datasource:
##  url: jdbc:mysql://localhost:3306/users
##  username: user
##  password: miBD
##  driver: com.mysql.cj.jdbc.Driver
##jpa:
##  hibernate:
##    ddl-auto: update
##  show-sql: true
##  properties:
##    hibernate:
##      dialect: org.hibernate.dialect.MySQL8Dialect
#

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: user
    password: miBD
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
      #  dialect: org.hibernate.dialect.MySQL8Dialect=com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE

eureka:
  instance:
    prefer-ip-address: true #muestra las ip de los servicios en vez de los nombres
  client:
    fetch-registry: true #registra el servidor cliente
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka #apunta al mismo host de aureka, 8761 es el port por defecto de aureka
